package br.com.pag.pedidos.model;

import java.util.Date;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Classe responsável pelo mapeamento da tabela cliente do dynamodb para um
 * objeto de dominio java.
 * 
 * @author Saulo Machado
 *
 */
@DynamoDBTable(tableName = "cliente")
@DynamoDBDocument
public class ClienteModel {

	private String id;
	@NotNull(message = "O CPF é obrigatório")
	@NotEmpty(message = "O CPF é obrigatório")
	@Size(max = 14, message = "O campo de CPF deve ter no máximo 14 caracteres")
	private String cpf;
	@Size(max = 100, message = "O campo de nome deve ter no máximo 100 caracteres")
	@NotNull(message = "O Nome é obrigatório")
	@NotEmpty(message = "O Nome não pode estar vazio")
	private String nome;
	@NotNull(message = "A Data de nascimento é obrigatório")
	private Date dataNascimento;

	public ClienteModel(String id,
			@NotNull(message = "O CPF é obrigatório") @NotEmpty(message = "O CPF é obrigatório") @Size(max = 14, message = "O campo de CPF deve ter no máximo 14 caracteres") String cpf,
			@Size(max = 200, message = "O campo de nome deve ter no máximo 200 caracteres") @NotNull(message = "O Nome é obrigatório") @NotEmpty(message = "O nome não pode estar vazio") String nome,
			@NotNull(message = "A Data de nascimento é obrigatório") Date dataNascimento) {
		super();
		this.id = id;
		this.cpf = cpf;
		this.nome = nome;
		this.dataNascimento = dataNascimento;
	}

	public ClienteModel() {
		super();
	}

	public ClienteModel(String id, String cpf) {
		super();
		this.id = id;
		this.cpf = cpf;
	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBRangeKey
	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@DynamoDBAttribute
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@DynamoDBAttribute
	public Date getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

}
