package br.com.pag.pedidos.model;

import java.math.BigDecimal;
import java.util.*;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Classe responsável pelo mapeamento da tabela pedido do dynamodb para um
 * objeto de dominio java.
 * 
 * @author Saulo Machado
 *
 */
@DynamoDBTable(tableName = "pedido")
@DynamoDBDocument
public class PedidoModel {

	private String id;
	private ClienteModel cliente;
	private BigDecimal valor;
	private List<ItemPedidoModel> itensPedido;
	
	public PedidoModel(String id, ClienteModel cliente, BigDecimal valor) {
		super();
		this.id = id;
		this.cliente = cliente;
		this.valor = valor;
	}

	public PedidoModel() {
		super();
	}

	public PedidoModel(String id) {
		super();
		this.id = id;
	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public ClienteModel getCliente() {
		return cliente;
	}

	public void setCliente(ClienteModel cliente) {
		this.cliente = cliente;
	}

	@DynamoDBAttribute
	public BigDecimal getValor() {
		return valor;
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	@DynamoDBAttribute
	public List<ItemPedidoModel> getItensPedido() {
		return itensPedido;
	}

	public void setItensPedido(List<ItemPedidoModel> itensPedido) {
		this.itensPedido = itensPedido;
	}
	
	

}
