package br.com.pag.pedidos.model;

import java.math.BigDecimal;

import javax.validation.constraints.NotEmpty;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Classe responsável pelo mapeamento da tabela produto do dynamodb para um
 * objeto de dominio java.
 * 
 * @author Saulo Machado
 *
 */
@DynamoDBTable(tableName = "produto")
@DynamoDBDocument
public class ProdutoModel {

	private String id;
	@Size(max = 100, message = "O campo de nome deve ter no máximo 100 caracteres")
	@NotNull(message = "O Nome é obrigatório")
	@NotEmpty(message = "O Nome não pode estar vazio")
	private String nome;
	private BigDecimal precoSugerido;

	public ProdutoModel(String id, String nome, BigDecimal precoSugerido) {
		super();
		this.id = id;
		this.nome = nome;
		this.precoSugerido = precoSugerido;
	}

	public ProdutoModel() {
		super();
	}

	public ProdutoModel(String id) {
		super();
		this.id = id;
	}

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DynamoDBAttribute
	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@DynamoDBAttribute
	public BigDecimal getPrecoSugerido() {
		return precoSugerido;
	}

	public void setPrecoSugerido(BigDecimal precoSugerido) {
		this.precoSugerido = precoSugerido;
	}

}
